name: theworldbaby
favicon: null
layout_spectrum: 0.7501551415771246
typography_spectrum: 0.42505322862416506
title: 'The World, Baby!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1017'
    - '#ffffff'
    - '#757a7f'
    - '#ff3870'
    - '#f3c780'
  brandStrength: 0.8367557597812265
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.37191032408736646
purpose: []
