name: theworldbaby
favicon: null
layout_spectrum: 0.7501551415771246
typography_spectrum: 0.42505322862416506
title: 'The World, Baby!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8367557597812265
  lightness: 0.651203534565866
  saturation: 0.3543237482663244
  rhythmicContrast: 0.37191032408736646
purpose: []
