name: 'The World, Baby'
favicon: null
layout_spectrum: 0.03322
typography_spectrum: 0.59268
title: 'The World, Baby!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1017'
    - '#ffffff'
    - '#757a7f'
    - '#ff3870'
    - '#f3c780'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.37191032408736646
purpose: []
